name: dropzone
description: Flet Dropzone control
repository: https://github.com/shiena/dropzone/src/flutter/dropzone
version: 0.1.0
homepage: https://github.com/shiena/dropzone

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  desktop_drop: ^0.5.0
  flet: 0.26.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
